### ISSUE TITLE
[Bug]: okhttp3  Response bodies must be closed

### ISSUE THREAD

**Issue by s-hintz** [flipt-io/flipt#2788] opened 2024-02-19 13:26 UTC
### Bug Description

Because auf Flipt, we get this log message:

`A connection to …  was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);`

See Response.kt from okhttp3:

```
/**
   * Returns a non-null value if this response was passed to [Callback.onResponse] or returned
   * from [Call.execute]. Response bodies must be [closed][ResponseBody] and may
   * be consumed only once.
   *
   * This always returns null on responses returned from [cacheResponse], [networkResponse],
   * and [priorResponse].
   */
  @get:JvmName("body") val body: ResponseBody?,
```

### Version Info

flipt-java-1.0.1.jar

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Use `FliptClient.java`.

### Expected Behavior

The response.body should be closed in `Evaluation.java`.

**Comment by markphelps** [comment] 2024-02-19 14:44
Thank you @s-hintz . Closing as dupe of https://github.com/flipt-io/flipt-server-sdks/issues/114

New release is going out now with the fix

Thank you for reporting!

**Closed by markphelps** 2024-02-19 14:44 UTC
Labels: bug
