### ISSUE TITLE
flipt import reports errors that flipt validate does not

### ISSUE THREAD

**Issue by ahobson** [flipt-io/flipt#2086] opened 2023-09-06 17:12 UTC
### Describe the Bug

Running `flipt import` on a file where the rules reference a variant does not exist results in an error, but `flipt validate` does not report the error. In addition, running the same import a second time does not report any error.

### Version Info

```
Version: dev
Commit: a4d2662d417fb60c70d0cb63c78927253e38683f
Build Date: 2023-09-06T16:02:41Z
Go Version: go1.20.6
OS/Arch: darwin/arm64
```

### To Reproduce

```
# in one window, start flipt
./bin/flipt
# in another window 
./bin/flipt validate test.features.yaml
# no errors
./bin/flipt import --address http://localhost:8080 --create-namespace test.features.yaml
# this fails with
# Error: finding variant: not_a_variant; flag: bogus_rule_variant
./bin/flipt import --address http://localhost:8080 --create-namespace test.features.yaml
# This time it succeeds?
```

### Expected Behavior

Ideally, this would be an error `flipt validate` would be able to catch.

Ideally, the 2nd import would produce the same error.

#### Attach an Export

GitHub tells me it does not support attaching YAML files, so here's the file:

```yaml
namespace: test
flags:
  - key: bogus_rule_variant
    name: Bogus Rule Variant
    enabled: false
    variants:
      - key: bogus_one
        name: One
      - key: bogus_two
        name: Two
    rules:
      - segment: test-segment
        distributions:
          - variant: not_a_variant
            rollout: 100

segments:
  - key: test-segment
    name: Test Segement
    constraints:
      - type: STRING_COMPARISON_TYPE
        property: propertyOne
        operator: eq
        value: thingOne
    match_type: ALL_MATCH_TYPE
```

**Comment by GeorgeMac** [comment] 2023-09-06 17:23
Hmm lots of interesting observations here.

One thing we've considered (actually intended to plan) is to have `flipt validate` actually attempt build an in-memory snapshot. This might actually capture the variant not found error you've mentioned here (this needs to be confirmed).

Second is that it is super weird it doesn't fail the second time.
That said, `flipt import` is a not an idempotent operation. If it fails mid way through it will leave your instance in a half complete state. I wonder if that is why we see different behaviour from one call to the next.
We've talked about moving this operation to mostly occur server-side, instead of client side, this could allow us to make the operation idempotent.

**Comment by ahobson** [comment] 2023-09-06 18:32
I can understand that the import isn't idempotent. That would be a neat feature, but not required IMHO.

I do find it interesting that the state of the system alters what is and is not an error on import. That seems a bit concerning to me as it suggests different orders of operations could result in a different state for the feature flags or that some checks are only on one part of the code path.

**Comment by GeorgeMac** [comment] 2023-09-07 08:17
@ahobson I am wondering if it less that it changed the state of the error and more that it is failing silently because the flag is already created. i.e. it is failing before getting to the create distribtribution.

**Comment by GeorgeMac** [comment] 2023-09-07 08:41
Yep, there is a bug on the new create namespace error 👍

**Comment by GeorgeMac** [comment] 2023-09-07 09:26
This is tagentially related issue https://github.com/flipt-io/validate-action/issues/19
In that, the solution of using the same snapshot building logic could solve both issues.

Here is the function we would likely leverage or alter to suit validates needs:
https://github.com/flipt-io/flipt/blob/main/internal/storage/fs/snapshot.go#L77-L100

Reflecting on the implementation:
https://github.com/flipt-io/flipt/blob/a4d2662d417fb60c70d0cb63c78927253e38683f/internal/storage/fs/snapshot.go#L364-L367

We would need to make this `continue` into an error to get the same observed behaviour on `import`.
Currently, we're dropping distributions silently that reference non-existent variants.

**Comment by GeorgeMac** [comment] 2023-09-07 12:33
That said, this would be a slight behaviour change from the current setup ☝️ 
If we changed these silent referential integrity failures to actually start erroring, someone might be relying on it.

We could instead warn on them inline. Then we could add a `--strict` flag to `flipt validate`.
The criteria here would be you could opt in to failing `flipt validate` when referential integrity is violated.

This is all in the spirit of backwards compat with existing behaviour in the filesystem backend.

**Comment by ahobson** [comment] 2023-09-07 13:44
For me, I would vote that silently dropping invalid data is not something that needs a backwards compatibility promise.

**Closed** 2023-09-13 12:57 UTC
Labels: bug

**Comment by GeorgeMac** [comment] 2023-09-13 13:00
This should be in 1.27.0 which should hopefully land this week
